name: FwGuilds
version: '${project.version}'
main: fw.fwguilds.FwGuilds
api-version: 1.18
load: STARTUP
authors: [ filipton ]
description: Yeah
website: filipton.xyz

commands:
  fwguilds:
    description: fwGuilds main Command
    usage: /fwguilds
    aliases:
      - fg
      - g
  baza:
    description: Tp to bazy
    usage: /baza
  ucieczka:
    description: Ucieczka z bazy przeciwnika
    usage: /ucieczka
  samobojstwo:
    description: Wykonujesz samobojstwo
    usage: /samobojstwo